import TodayTask from "./components/TodayTask";

export const data = {
  loggedInUser: {
    id: 12345,
    name: "Jane Doe",
    email: "janedoe@example.com",
    avatar: "/Profil.png",
    role: "admin",
    following: [601, 602],
    preferences: {
      theme: "light",
      language: "en",
      notificationsEnabled: true,
      timezone: "+3:00",
      timeFormat: "UTC",
      timezoneFormat: "24h",
    },
  },
  notifications: [
    {
      id: 1,
      type: "message",
      description: "You have a new message from Alice.",
      timestamp: "2025-03-06T12:00:00Z",
      read: false,
    },
    {
      id: 2,
      type: "system",
      description: "Your password will expire in 3 days.",
      timestamp: "2025-03-05T15:30:00Z",
      read: true,
    },
    {
      id: 3,
      type: "reminder",
      description: "Meeting with the team at 2 PM.",
      timestamp: "2025-03-06T09:00:00Z",
      read: false,
    },
  ],
  tasks: [
    {
      id: 1,
      createdAt: "2025-03-06T08:45:00Z",
      imageUrl: "/Image.png",
      category: "UI/UX Design",
      tag: "Urgent",
      title: "Create Mobile App Wireframes",
      description:
        "Design comprehensive wireframes for a mobile e-commerce application using Figma. Focus on user flow, navigation patterns, and responsive design principles.",
      assignees: ["/avatar4.png", "/avatar5.png"],
      progress: 50,
      // Detail parameters
      thumbnail: "/Image.png",
      duration: "15:30",
      currentTime: "5:20",
      studentsInvolved: 25,
      durationHours: 2,
      categories: ["UI/UX Design", "Mobile Design"],
      assessment: [
        "Create low-fidelity wireframes for all main screens",
        "Design user flow diagrams for key user journeys",
        "Implement responsive design principles",
        "Present wireframes to mentor for feedback",
      ],
      student: {
        name: "Sarah Chen",
        class: "UI/UX Design Fundamentals",
        number: "1",
      },
      lastModified: "6 March 2025",
    },
    {
      id: 2,
      createdAt: "2025-03-05T14:20:00Z",
      imageUrl: "/Image3.png",
      category: "Web Development",
      tag: "Important",
      title: "Build React Component Library",
      description:
        "Create a reusable component library using React and TypeScript. Focus on accessibility, documentation, and consistent design patterns.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar3.png",
        "/avatar5.png",
      ],
      progress: 90,
      // Detail parameters
      thumbnail: "/Image3.png",
      duration: "8:45",
      currentTime: "8:00",
      studentsInvolved: 1,
      durationHours: 1,
      categories: ["React", "TypeScript", "Component Design"],
      assessment: [
        "Design and implement Button, Input, and Card components",
        "Add TypeScript interfaces and proper prop validation",
        "Write comprehensive Storybook documentation",
        "Implement accessibility features (ARIA labels, keyboard navigation)",
      ],
      student: {
        name: "Marcus Johnson",
        class: "Advanced React Development",
        number: "2",
      },
      lastModified: "5 March 2025",
    },
    {
      id: 3,
      createdAt: "2025-03-04T10:10:00Z",
      imageUrl: "/Image2.png",
      category: "JavaScript",
      tag: "Medium",
      title: "Master Advanced JavaScript Concepts",
      description:
        "Deep dive into advanced JavaScript topics including closures, prototypes, async/await, and functional programming patterns.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar3.png",
        "/avatar4.png",
      ],
      progress: 80,
      // Detail parameters
      thumbnail: "/Image2.png",
      duration: "45:20",
      currentTime: "36:15",
      studentsInvolved: 150,
      durationHours: 3,
      categories: ["JavaScript", "Advanced Programming"],
      assessment: [
        "Implement closure-based module pattern",
        "Create custom prototype methods and inheritance",
        "Build async data fetching with error handling",
        "Apply functional programming concepts (map, reduce, filter)",
      ],
      student: {
        name: "Alex Rodriguez",
        class: "JavaScript Mastery",
        number: "3",
      },
      lastModified: "4 March 2025",
    },
    {
      id: 4,
      createdAt: "2025-03-03T16:30:00Z",
      imageUrl: "/Image3.png",
      category: "DevOps",
      tag: "High",
      title: "Set Up CI/CD Pipeline",
      description:
        "Configure automated testing, building, and deployment pipeline using GitHub Actions and Docker containers.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar4.png",
        "/avatar5.png",
      ],
      progress: 25,
      // Detail parameters
      thumbnail: "/Image3.png",
      duration: "20:15",
      currentTime: "5:30",
      studentsInvolved: 8,
      durationHours: 2,
      categories: ["DevOps", "GitHub Actions", "Docker"],
      assessment: [
        "Configure automated testing workflow",
        "Set up Docker containerization",
        "Implement staging and production deployments",
        "Monitor pipeline performance and reliability",
      ],
      student: {
        name: "David Kim",
        class: "DevOps Engineering",
        number: "4",
      },
      lastModified: "3 March 2025",
    },
    {
      id: 5,
      createdAt: "2025-03-02T09:15:00Z",
      imageUrl: "/Image4.png",
      category: "Mobile Development",
      tag: "Low",
      title: "Develop iOS App with SwiftUI",
      description:
        "Build a complete iOS application using SwiftUI framework, implementing MVVM architecture and Core Data for persistence.",
      assignees: ["/avatar3.png", "/avatar4.png", "/avatar5.png"],
      progress: 30,
      // Detail parameters
      thumbnail: "/Image4.png",
      duration: "12:30",
      currentTime: "3:45",
      studentsInvolved: 3,
      durationHours: 1,
      categories: ["iOS Development", "SwiftUI", "Mobile Apps"],
      assessment: [
        "Design app architecture using MVVM pattern",
        "Implement Core Data for local storage",
        "Create responsive UI with SwiftUI components",
        "Add navigation and state management",
      ],
      student: {
        name: "Emma Thompson",
        class: "iOS Development Bootcamp",
        number: "5",
      },
      lastModified: "2 March 2025",
    },
    {
      id: 6,
      createdAt: "2025-03-01T11:45:00Z",
      imageUrl: "/Image.png",
      category: "Data Science",
      tag: "Medium",
      title: "Build Machine Learning Model",
      description:
        "Create a predictive model using Python, scikit-learn, and pandas. Focus on data preprocessing, feature engineering, and model evaluation.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar3.png",
        "/avatar4.png",
        "/avatar5.png",
      ],
      progress: 60,
      // Detail parameters
      thumbnail: "/Image.png",
      duration: "25:45",
      currentTime: "15:20",
      studentsInvolved: 5,
      durationHours: 2,
      categories: ["Machine Learning", "Python", "Data Analysis"],
      assessment: [
        "Clean and preprocess dataset",
        "Perform exploratory data analysis",
        "Implement feature engineering techniques",
        "Train and evaluate multiple ML algorithms",
      ],
      student: {
        name: "Priya Patel",
        class: "Data Science Fundamentals",
        number: "6",
      },
      lastModified: "1 March 2025",
    },
    {
      id: 7,
      createdAt: "2025-02-28T13:00:00Z",
      imageUrl: "/Image1.png",
      category: "Web Development",
      tag: "High",
      title: "Master Full-Stack Development",
      description:
        "Build a complete web application using React frontend, Node.js backend, and PostgreSQL database with authentication and API integration.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar4.png",
        "/avatar5.png",
      ],
      progress: 80,
      // Detail parameters
      thumbnail: "/Image1.png",
      duration: "60:00",
      currentTime: "48:30",
      studentsInvolved: 300,
      durationHours: 1,
      categories: ["Full-Stack", "React", "Node.js"],
      assessment: [
        "Design and implement RESTful API endpoints",
        "Create responsive React components",
        "Implement user authentication and authorization",
        "Deploy application to cloud platform",
      ],
      student: {
        name: "Jordan Lee",
        class: "Full-Stack Development",
        number: "7",
      },
      lastModified: "28 February 2025",
    },
    {
      id: 8,
      createdAt: "2025-02-27T15:40:00Z",
      imageUrl: "/Image2.png",
      category: "Cybersecurity",
      tag: "Medium",
      title: "Implement Security Best Practices",
      description:
        "Learn and implement web application security measures including OWASP Top 10, authentication, encryption, and vulnerability assessment.",
      assignees: [
        "/avatar1.png",
        "/avatar2.png",
        "/avatar3.png",
        "/avatar4.png",
        "/avatar5.png",
      ],
      progress: 75,
      // Detail parameters
      thumbnail: "/Image2.png",
      duration: "5:15",
      currentTime: "3:50",
      studentsInvolved: 1,
      durationHours: 1,
      categories: ["Cybersecurity", "Web Security", "OWASP"],
      assessment: [
        "Implement secure authentication mechanisms",
        "Apply input validation and sanitization",
        "Configure HTTPS and security headers",
        "Perform security testing and vulnerability assessment",
      ],
      student: {
        name: "Michael Chen",
        class: "Cybersecurity Fundamentals",
        number: "8",
      },
      lastModified: "27 February 2025",
    },
    {
      id: 9,
      createdAt: "2025-02-26T10:00:00Z",
      imageUrl: "/Image3.png",
      category: "DevOps",
      tag: "Urgent",
      title: "Container Orchestration with Kubernetes",
      description:
        "Learn Kubernetes fundamentals and deploy containerized applications using pods, services, and deployments.",
      assignees: ["/avatar1.png", "/avatar2.png", "/avatar5.png"],
      progress: 80,
      // Detail parameters
      thumbnail: "/Image3.png",
      duration: "18:30",
      currentTime: "14:45",
      studentsInvolved: 3,
      durationHours: 2,
      categories: ["Kubernetes", "DevOps", "Containerization"],
      assessment: [
        "Set up local Kubernetes cluster",
        "Deploy applications using YAML manifests",
        "Configure services and ingress controllers",
        "Implement health checks and monitoring",
      ],
      student: {
        name: "Ryan O'Connor",
        class: "DevOps Engineering",
        number: "9",
      },
      lastModified: "26 February 2025",
    },
    {
      id: 10,
      createdAt: "2025-02-25T14:30:00Z",
      imageUrl: "/Image4.png",
      category: "UI/UX Design",
      tag: "Important",
      title: "Design System Implementation",
      description:
        "Create a comprehensive design system with color palettes, typography, spacing, and reusable component patterns.",
      assignees: ["/avatar1.png", "/avatar2.png", "/avatar3.png"],
      progress: 80,
      // Detail parameters
      thumbnail: "/Image4.png",
      duration: "8:20",
      currentTime: "6:45",
      studentsInvolved: 1,
      durationHours: 1,
      categories: ["Design Systems", "UI/UX", "Design Tokens"],
      assessment: [
        "Define color palette and typography scale",
        "Create spacing and layout guidelines",
        "Design reusable component library",
        "Document design system usage guidelines",
      ],
      student: {
        name: "Sophie Williams",
        class: "UI/UX Design Systems",
        number: "10",
      },
      lastModified: "25 February 2025",
    },
    {
      id: 11,
      createdAt: "2025-02-24T12:00:00Z",
      imageUrl: "/Image.png",
      category: "Android Development",
      tag: "Medium",
      title: "Build Android App with Kotlin",
      description:
        "Develop a native Android application using Kotlin, Jetpack Compose, and modern Android architecture components.",
      assignees: [
        "/avatar2.png",
        "/avatar3.png",
        "/avatar4.png",
        "/avatar5.png",
      ],
      progress: 90,
      // Detail parameters
      thumbnail: "/Image.png",
      duration: "22:15",
      currentTime: "20:00",
      studentsInvolved: 4,
      durationHours: 2,
      categories: ["Android", "Kotlin", "Jetpack Compose"],
      assessment: [
        "Set up Android development environment",
        "Create UI using Jetpack Compose",
        "Implement MVVM architecture with ViewModel",
        "Add navigation and data persistence",
      ],
      student: {
        name: "Carlos Mendez",
        class: "Android Development",
        number: "11",
      },
      lastModified: "24 February 2025",
    },
    {
      id: 12,
      createdAt: "2025-02-23T08:00:00Z",
      imageUrl: "/Image1.png",
      category: "Programming",
      tag: "Low",
      title: "Algorithm and Data Structures Practice",
      description:
        "Solve coding challenges focusing on algorithms, data structures, and problem-solving techniques using various programming languages.",
      assignees: ["/avatar1.png", "/avatar2.png", "/avatar5.png"],
      progress: 70,
      // Detail parameters
      thumbnail: "/Image1.png",
      duration: "30:45",
      currentTime: "21:30",
      studentsInvolved: 3,
      durationHours: 1,
      categories: ["Algorithms", "Data Structures", "Problem Solving"],
      assessment: [
        "Implement sorting and searching algorithms",
        "Solve problems using arrays, linked lists, and trees",
        "Optimize solutions for time and space complexity",
        "Practice with dynamic programming concepts",
      ],
      student: {
        name: "Aisha Kumar",
        class: "Computer Science Fundamentals",
        number: "12",
      },
      lastModified: "23 February 2025",
    },
  ],
};

export const navigation = [
  { title: "Overview", icon: "fa-home", path: "/" },
  { title: "Tasks", icon: "fa-tasks", path: "/tasks" },
  { title: "Mentors", icon: "fa-user-circle", path: "/mentors" },
  { title: "Settings", icon: "fa-cog", path: "/settings" },
];

export const mentors = [
  {
    id: 601,
    name: "Jessica Jane",
    role: "Web Developer",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40,
    ],
    stars: 4.7,
    reviews: 750,
    bio: "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development. I specialize in modern JavaScript frameworks and full-stack development.",
    avatar: "/photo8.png",
    dateJoined: "2024-01-15",
  },
  {
    id: 602,
    name: "Alex Stanton",
    role: "UI/UX Designer",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60,
    ],
    stars: 4.9,
    reviews: 970,
    bio: "Hi, I'm Alex Stanton. I am a doctoral student at Oxford University majoring in UI/UX Design. I focus on creating intuitive and beautiful user experiences.",
    avatar: "/photo.png",
    dateJoined: "2023-11-20",
  },
  {
    id: 603,
    name: "Antoine Griezmann",
    role: "Android Developer",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    ],
    stars: 4.8,
    reviews: 830,
    bio: "Hi, I'm Antoine Griezmann. I'm an Android Developer at Google company. I specialize in native Android development and Kotlin programming.",
    avatar: "/photo.png",
    dateJoined: "2024-02-01",
  },
  {
    id: 604,
    name: "Anna White",
    role: "3D Design",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60,
    ],
    stars: 4.8,
    reviews: 870,
    bio: "Hi, I'm Anna White. I'm a professional 3D Designer at Blender company. I create stunning 3D models and animations for various industries.",
    avatar: "/photo2.png",
    dateJoined: "2024-03-10",
  },
  {
    id: 605,
    name: "Richard Kyle",
    role: "2D Design",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60,
    ],
    stars: 4.7,
    reviews: 730,
    bio: "Hi, I'm Richard Kyle. I'm a professional 2D Designer at Photoshop company. I specialize in graphic design and digital illustration.",
    avatar: "/photo3.png",
    dateJoined: "2023-12-01",
  },
  {
    id: 606,
    name: "Julia Philips",
    role: "IOS Developer",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60,
    ],
    stars: 4.9,
    reviews: 910,
    bio: "Hi, I'm Julia Philips. I'm a senior manager at Apple company. I lead iOS development teams and create innovative mobile applications.",
    avatar: "/photo4.png",
    dateJoined: "2024-01-25",
  },
  {
    id: 607,
    name: "George Green",
    role: "DevOps",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45,
    ],
    stars: 4.3,
    reviews: 15,
    bio: "DevOps engineer specializing in automation and cloud infrastructure.",
    avatar: "/photo5.png",
    dateJoined: "2024-02-15",
  },
  {
    id: 608,
    name: "Hannah Taylor",
    role: "Cybersecurity",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40,
    ],
    stars: 4.8,
    reviews: 40,
    bio: "Cybersecurity expert dedicated to protecting digital assets and data.",
    avatar: "/photo6.png",
    dateJoined: "2023-11-10",
  },
  {
    id: 609,
    name: "Isaac Moore",
    role: "AI/ML",
    tasks: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25,
    ],
    stars: 4.5,
    reviews: 25,
    bio: "AI/ML researcher focused on developing innovative machine learning solutions.",
    avatar: "/photo7.png",
    dateJoined: "2024-03-01",
  },
];

export const runningTasks = {
  allTasks: 100,
  running: 65,
  remainingTasks: 45,
};

export const activityTracker = {
  today: [
    { id: "today-0", day: "S", tasks: 1 },
    { id: "today-1", day: "M", tasks: 2 },
    { id: "today-2", day: "T", tasks: 1 },
    { id: "today-3", day: "W", tasks: 2 },
    { id: "today-4", day: "T", tasks: 3 },
    { id: "today-5", day: "F", tasks: 2 },
    { id: "today-6", day: "S", tasks: 2 },
  ],
  week: [
    { id: "week-0", day: "S", tasks: 3 },
    { id: "week-1", day: "M", tasks: 2 },
    { id: "week-2", day: "T", tasks: 3 },
    { id: "week-3", day: "W", tasks: 1 },
    { id: "week-4", day: "T", tasks: 3 },
    { id: "week-5", day: "F", tasks: 2 },
    { id: "week-6", day: "S", tasks: 1 },
  ],
};

export const TodayTaskData = {
  id: 1,
  createdAt: "2025-03-06T08:45:00Z",
  imageUrl: "/Image.png",
  category: "UI/UX Design",
  tag: "Urgent",
  title: "Create Mobile App Wireframes",
  description:
    "Design comprehensive wireframes for a mobile e-commerce application using Figma. Focus on user flow, navigation patterns, and responsive design principles.",
  assignees: ["/avatar4.png", "/avatar5.png"],
  progress: 50,
  // Detail parameters
  thumbnail: "/Image.png",
  duration: "15:30",
  currentTime: "5:20",
  studentsInvolved: 25,
  durationHours: 2,
  categories: ["UI/UX Design", "Mobile Design"],
  assessment: [
    "Create low-fidelity wireframes for all main screens",
    "Design user flow diagrams for key user journeys",
    "Implement responsive design principles",
    "Present wireframes to mentor for feedback",
  ],
  student: {
    name: "Sarah Chen",
    class: "UI/UX Design Fundamentals",
    number: "1",
  },
  lastModified: "6 March 2025",
};
